# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Samples from a Uniform Distribution
#'
#' Generates random values from a uniform distribution using the C++ standard
#' library's `<random>` facilities, which have been part of standard C++ since
#' C++11.
#'
#' @param n     Number of observations to generate.
#' @param start Lower bound of the distribution.
#' @param end   Upper bound of the distribution.
#' @param seed  Seed for the random number generator.
#'
#' @return
#' A `numeric` vector of `n` draws from the Uniform(`start`, `end`)
#' distribution.
#'
#' @export
#' @examples
#' # Generate one draw
#' runif_cpp(1, start = 2, end = 20)
#'
#' # Generate two draws
#' runif_cpp(2, start = 5, end = 30)
runif_cpp <- function(n, start = 0.0, end = 1.0, seed = 183L) {
    .Call(`_r11_runif_cpp`, n, start, end, seed)
}

